@baseUrl = http://localhost:3000/users

### Get all users
GET {{baseUrl}}
###

### Get user by id
GET {{baseUrl}}/65e7241a1492a6af5919b5ba

### GET {{baseUrl}}/items/:id

### Add user
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "emma",
    "lastName": "flowers",
    "email": "cello@gmail.io",
    "favoriteColor": "electric blue",
    "birthday": "november 11"
}
###

### Add user
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "andres",
    "lastName": "carba",
    "email": "viola@gmail.io",
    "favoriteColor": "deep jungle green",
    "birthday": "march 6"
}
###

### Update user
PUT {{baseUrl}}/65e7241a1492a6af5919b5ba
Content-Type: application/json

{
    "email": "lom@gmail.com",
    "birthday": "august 26",
    "favoriteColor": "purple",
    "firstName": "kenia",
    "lastName": "bernal"
}

### DELETE Delete user
DELETE {{baseUrl}}/65f126effd0a8a20bc354291